source "https://rubygems.org"

gem "base64"
gem "bigdecimal"
gem "csv"
gem "jekyll", "~> 3.10"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "kramdown-parser-gfm"
gem "logger"
gem "webrick", "~> 1.9"
